<?php

namespace Plugin\LowStockAlert\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LowStockAlertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LowStockAlertRepository extends EntityRepository
{
}
